### ISSUE TITLE
TIDAL PlugIn Playback broken

### ISSUE THREAD

**Issue by marcelo-g-simas** [LMS-Community/slimserver#417]
Today I noticed that playback using the TIDAL plugin no longer works.  I get the message "Invalid or inexistent track ID" in my squeeze radios, no error message but no sound on a squeezebox v2 player and see the following entries in the server log:
```
[20-09-05 23:03:44.4776] Slim::Plugin::WiMP::ProtocolHandler::_gotBulkMetadata (395) Error fetching track metadata: Invalid JSON response
[20-09-05 23:04:26.5045] Slim::Plugin::WiMP::ProtocolHandler::_gotBulkMetadata (395) Error fetching track metadata: Invalid JSON response
```
I am running Logitech Media Server Version: 7.9.3 - 1590417116 on Ubuntu 18.04 LTS.  The TIDAL PlugIn is v 1.2.

**Comment by michaelherger** [comment]
Would you have a subscription which allows for FLAC streaming, or lossy only? Could you please share your TIDAL username with Michael ät slim devices dot com? This would likely help me to find hints in our log files.

**Comment by marcelo-g-simas** [comment]
I had a premium subscription, which does not have lossless FLAC streaming.  So I upgraded to Hi-Fi and changed the PlugIn to use "FLAC or AAC" and the devices are playing again.  If I switch the PlugIn back back to AAC/320kbps I get "Invalid or inexistent track ID" again.  I will send the TIDAL creds directly to Michael.

**Comment by marcelo-g-simas** [comment]
Email sent, let me know if you don't get it.  It will come from msimas ät gmail dot com.

**Comment by michaelherger** [comment]
Thanks a lot! That should be helpful.

I found a bunch of "Session does not have streaming privileges" errors for your account. BUT in this case you should get that literal response back, not the "Invalid track ID" you're seeing... 

Could you please update your LMS to the very latest to see whether this makes any difference? What type of player would you have?

**Comment by marcelo-g-simas** [comment]
I am already running 7.9.3 which seems to be the latest build available here: http://downloads.slimdevices.com/.  Is there another place where I can download built packages, I could install from source but would rather not risk putting the system in a broken state.  Here are the players I have in my network:

```
Player Model: Squeezebox Radio
Player Type: baby
Firmware: 7.7.3-r16676
 
Player Model: Squeezebox Radio
Player Type: baby
Firmware: 7.7.3-r16676
 
Player Model: Squeezebox Radio
Player Type: baby
Firmware: 7.7.3-r16676
 
Player Model: Squeezebox Classic
Player Type: squeezebox2
Firmware: 137
```

**Comment by michaelherger** [comment]
The LMS revision you mentioned in your initial report is outdated. It's a nightly build from back in May, a few weeks before the important changes were applied. Please update to the final release from http://downloads.slimdevices.com/LogitechMediaServer_v7.9.3/.

**Comment by marcelo-g-simas** [comment]
Ok, installed the latest 7.9.3 and now streaming AAC works again.  Thanks for the support!

**Comment by marcelo-g-simas** [comment]
This problem has come back, with the latest 7.9.3 release.  Maybe something changed on TIDAL's side?

**Comment by marcelo-g-simas** [comment]
The players print the message "Failed to pay stream [song name]" advance to the next item on the playlist until it reaches the end.

**Comment by marcelo-g-simas** [comment]
After restarting everything, uninstalling the TIDAL plugin, removing the TIDAL account and re-adding I get the message "Problem: Can't connect to server to server for: [song name]" on the players and the same behavior (no sound and skips over playlist until the end).  This is what the log on the server looks like:

```
[20-10-15 18:19:18.2372] main::init (387) Starting Logitech Media Server (v7.9.3, 1597753178, Sun Aug 23 19:21:22 CEST 2020) perl 5.026001 - x86_64-linux-gnu-thread-multi
[20-10-15 18:19:20.0896] Slim::Web::Cometd::handler (421) errorNeedsClient: 00:04:20:2c:80:22, status, -, 10, menu:menu, useContextMenu:1, subscribe:600
[20-10-15 18:20:58.0369] Slim::Player::Song::open (472) Warning: stream failed to open [wimp://1330423.mp4].
[20-10-15 18:23:45.8150] Slim::Player::Song::open (472) Warning: stream failed to open [wimp://3972564.mp4].
[20-10-15 18:23:46.0223] Slim::Player::Song::open (472) Warning: stream failed to open [wimp://4010395.mp4].
[20-10-15 18:23:46.3593] Slim::Player::Song::open (472) Warning: stream failed to open [wimp://13482413.mp4].
[20-10-15 18:23:46.5642] Slim::Player::Song::open (472) Warning: stream failed to open [wimp://1381746.mp4].
[20-10-15 18:23:46.7609] Slim::Player::Song::open (472) Warning: stream failed to open [wimp://77631647.mp4].
[20-10-15 18:23:47.0074] Slim::Player::Song::open (472) Warning: stream failed to open [wimp://1336404.mp4].
[20-10-15 18:23:47.2257] Slim::Player::Song::open (472) Warning: stream failed to open [wimp://77826772.mp4].
```

**Comment by mherger** [comment]
They switched streaming protocol over night. Should be working again.

**Comment by marcelo-g-simas** [comment]
It’s still broken, restarted LMS and got the same result: “Failed to play stream [song name]”

**Comment by michaelherger** [comment]
Do you see the problem with all players or only the Classic? Are they synchronised?

In order for the Classic to be able to stream AAC you'll need LMS8. Radio should work.

**Comment by tmancill** [comment]
I signed up for a trial of TIDAL and was easily able to configure the plugin with LMS, but I was never able to get anything to play on my Squeezebox Booms.  Playback on my squeezelite-based players functioned as expected.  This was about a month ago and I tried with LMS 7.9.3, and I believe also with LMS 8.

Would the fix for the Classic apply to the Boom also?  (Should I try again with LMS 8?)

**Comment by michaelherger** [comment]
Yes, in order to stream lossy TIDAL to Boom/Classic you'd need a recent LMS8. But please note that we're currently seeing issues streaming TIDAL in certain regions.

**Comment by marcelo-g-simas** [comment]
I went to LMS 8.0 and still no cigar streaming.  I believe what I am seeing is the same as #438.
